// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"learnGo/wire/config"
	"learnGo/wire/repo"
	"learnGo/wire/service"
)

import (
	_ "github.com/google/wire"
)

// Injectors from wire.go:

func initService() (service.Service, error) {
	configConfig := config.NewConfig()
	repoRepo := repo.NewRepo(configConfig)
	serviceService := service.NewService(repoRepo)
	return serviceService, nil
}
